SELECT TOP 1000 [MsgId]
      ,[SessionId]
      ,[TestId]
      ,[MsgTime]
      ,[PosId]
      ,[NetworkId]
      ,[Source]
      ,[Destination]
      ,[Encoding]
  FROM [Burda_Data_2015].[dbo].[MsgIPTraceHTTPInfo]