SELECT TOP 1000 [MsgId]
      ,[SessionId]
      ,[TestId]
      ,[MsgTime]
      ,[PosId]
      ,[NetworkId]
      ,[dir]
      ,[source]
      ,[destination]
      ,[size]
      ,[fragFlags]
      ,[srcPort]
      ,[dstPort]
      ,[sequenceNr]
      ,[ackNr]
      ,[tcpFlags]
      ,[windowSize]
  FROM [Burda_Data_2015].[dbo].[MsgIpTraceTCPPackets]