SELECT TOP 1000 [MsgId]
      ,[SessionId]
      ,[TestId]
      ,[MsgTime]
      ,[PosId]
      ,[NetworkId]
      ,[LTETopNId]
      ,[LTEHCId]
      ,[ScannerId]
      ,[Version]
      ,[RFBand]
      ,[Channel]
      ,[Bandwidth]
      ,[RSSI_0]
      ,[RSSI_1]
      ,[SortingValue]
      ,[NumRecords]
      ,[Message]
  FROM [Burda_Data_2015].[dbo].[MsgLTEScannerTopNInfo]
  WHERE SessionId like '2'
  ORDER BY MsgTime